### Load require libraries

```{r, echo=FALSE}
library(devtools)
library(magrittr)
```

### Document, install and load the package

```{r}
.libPaths()
document()
install()
load_all()
test()
```

### Load required libraries for the package

```{r}
libs2use <- c(
  "lobstr", "haven", "RSQLite", "RPostgres",
  "DBI", "odbc", "R6", "RMariaDB",
  "RMySQL", "getPass"
)

use_package("tidyverse", type = "depends")
libs2use %>% purrr::walk(use_package)
```

##### Test data generate

```{r}
library(DBI)
library(RSQLite)

con <- dbConnect(SQLite(), "tests/testthat/fixtures/test.db")

dbWriteTable(con, "mtcars", mtcars)

dbDisconnect(con)

saveRDS(mtcars, "tests/testthat/fixtures/test.rds")

test1 <- mtcars
test2 <- mtcars
save(test1, test2, file = "tests/testthat/fixtures/test.rda")

haven::write_xpt( mtcars, path = "tests/testthat/fixtures/test.xpt")
system("zip tests/testthat/fixtures/test.zip tests/testthat/fixtures/test.rds")
system("tar -cvf tests/testthat/fixtures/test.tar tests/testthat/fixtures/test.rds")

```

#### Stats

```{r}
get_obs(mtcars$hp)
get_range(mtcars$hp)
get_central(mtcars$hp)
get_var_sd(mtcars$hp)
get_iqr(mtcars$hp)
get_skewness(mtcars$hp)
get_kurtosis(mtcars$hp)
get_cv(mtcars$hp)
get_zscore(mtcars$hp)

test <- GetStat$new(mtcars)

test$obs()
test$range()
test$central()
test$var_sd()
test$iqr()
test$skewness()
test$kurtosis(c('hp', 'mpg'))
test$cv(c('hp', 'mpg'))
test$zscore(c('hp', 'mpg'))

dbpath <- "tests/testthat/fixtures/test.db"
lcars <- leer(dbpath)

lazy <- lcars$leer("mtcars") 
test1 <- GetStat$new(lazy) 
test1$obs()
test1$range()
test1$central()
test1$var_sd()
test1$iqr()
test1$skewness()
test1$kurtosis(c('hp', 'mpg'))
test1$cv(c('hp', 'mpg'))
test1$zscore(c('hp', 'mpg'))
```
